package:
  name: pyparsing
  version: "2.0.6"

source:
  fn: pyparsing-2.0.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.6.tar.gz
  md5: a2d85979e33a6600148c6383d3d8de67
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyparsing = pyparsing:main
    #
    # Would create an entry point called pyparsing that calls pyparsing.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyparsing.wikispaces.com/
  license: MIT License
  summary: 'Python parsing module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
