package:
  name: glypy
  version: "0.0.5"

source:
  fn: glypy-0.0.5.zip
  url: https://pypi.python.org/packages/source/g/glypy/glypy-0.0.5.zip
  md5: e2d2bf8092119518b7e1382c1c0e23e4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - glypy = glypy:main
    #
    # Would create an entry point called glypy that calls glypy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - hjson
    - six
    - requests
    - rdflib
    - sparqlwrapper
    - matplotlib >=1.4.3

  run:
    - python
    - hjson
    - six
    - requests
    - rdflib
    - sparqlwrapper
    - matplotlib >=1.4.3

test:
  # Python imports
  imports:
    - glypy
    - glypy.algorithms
    - glypy.composition
    - glypy.io
    - glypy.io.nomenclature
    - glypy.plot
    - glypy.structure
    - glypy.tests
    - glypy.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://glypy.readthedocs.org/en/master/
  license: UNKNOWN
  summary: 'UNKNOWN'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
